language: cpp

sudo: required
dist: trusty

env:
  global:
    - LIBHDFS3_SRC="~/libhdfs3"
    - LIBHDFS3_BUILD="~/libhdfs3-build"

before_install:
  - sudo apt-get update -qq
  # Install libhdfs3 dependencies
  - sudo apt-get install -y libxml2-dev uuid-dev libprotobuf-dev protobuf-compiler libgsasl7-dev libkrb5-dev libboost-all-dev
  # Build libhdfs3
  - git clone git://github.com/Pivotal-Data-Attic/pivotalrd-libhdfs3.git $LIBHDFS3_SRC
  - mkdir LIBHDFS3_BUILD
  - cd LIBHDFS3_BUILD
  - cmake $LIBHDFS3_SRC
  - make install
  # Install other libomptarget dependencies
  - sudo apt-get install -y libssh-dev libelf-dev libffi-dev python-pip sbt

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
