language: cpp

sudo: required
dist: trusty

env:
  global:
    - LIBHDFS3_SRC="$HOME/libhdfs3"
    - LIBHDFS3_BUILD="$HOME/libhdfs3-build"

before_install:
  - sudo apt-get update -qq
  # Install libhdfs3 dependencies
  - sudo apt-get install libxml2-dev uuid-dev libprotobuf-dev protobuf-compiler libgsasl7-dev libkrb5-dev libboost-all-dev
  # Build libhdfs3
  - git clone git://github.com/Pivotal-Data-Attic/pivotalrd-libhdfs3.git $LIBHDFS3_SRC
  - mkdir $LIBHDFS3_BUILD
  - cd $LIBHDFS3_BUILD
  - cmake $LIBHDFS3_SRC
  - sudo make install
  # Install other libomptarget dependencies
  - echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
  - sudo apt-get update
  - sudo apt-get install libssh-dev libelf-dev libffi-dev python-pip sbt

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
