language: cpp
sudo: required
dist: trusty
# Use https (public access) instead of git for git-submodules. This modifies only Travis-CI behavior!
# disable the default submodule logic
git:
  submodules: false
compiler:
- clang
- gcc
env:
  global:
  - LIBHDFS3_SRC="$HOME/libhdfs3"
  - LIBHDFS3_BUILD="$HOME/libhdfs3-build"
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot
before_install:
before_cache:
# Tricks to avoid unnecessary cache updates
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
before_install:
- sudo apt-get update -qq
- sudo apt-get install libxml2-dev uuid-dev libprotobuf-dev protobuf-compiler libgsasl7-dev
  libkrb5-dev libboost-all-dev
- git clone git://github.com/Pivotal-Data-Attic/pivotalrd-libhdfs3.git $LIBHDFS3_SRC
- mkdir $LIBHDFS3_BUILD
- cd $LIBHDFS3_BUILD
- cmake $LIBHDFS3_SRC
- sudo make install
- echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
- sudo apt-get update
- sudo apt-get install libssh-dev libelf-dev libffi-dev python-pip sbt
# use sed to replace the SSH URL with the public URL, then init and update submodules
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
script:
- mkdir $TRAVIS_BUILD_DIR/build
- cd $TRAVIS_BUILD_DIR/build
- cmake $TRAVIS_BUILD_DIR
- make
notifications:
  slack:
    secure: uSV6H8HfCRpnsTJtoAuUJwETja/iL8dtrWHBXXCrrN2PBm05xiG6Q9l7kgYlI6IueoNHabiyy+bklAdhww3w/jkWjia8HRwa+Y1KVZ8Ty++nU5fuFK/eq3/xyHBP6KsZnCGIVEWCBdPU2P6XJ1K8xSWUw7Qv+cNzpSQ9jF1OWIXOVTKj2j7clF7ji5AqwGNQGOnwYXunvbc6TKz0Eg9QJyI3gu5OWWfptD5HlcoYwGB+suQA1FaJSVhWRVC3zQYAvXmQ2wGpM7ZuJ7Xz9OeiOmDg6EpHIROkLmaUxE5Udl6oRhO3BHjNyDTM2RhXVgOGzjog5GJKf+IzOWdCPCnhAZ+LgaaFosgrG+MspRWP/GOlsVFJkgme114V6yBaMKRXlPascwovA1e3xsmSPKhHBnU2mTpLLelH2SfFeMmp28bxmr/gFyvYrwmiJn9SSf5Z0A7BuNazDg6fFxxMqZohu/GN7/aQVJn7MAjQ2ZGliVOFHgp0iHKUpCjoHwflWHSZWYQRshWONG7IJnD8p6uxhl5zxbU1UNh/C3L0oWNqbKFlwmbKYV6PYF85JaFVRAegvndHbfxOfbKdtKdPlsDSCOJW5k74Oo0Zsz2wcEA6vop53QYi0vIIKobBPdQ3IJnRopWBfW4YiId01YWxh0CfzWZTeQbNZ0r6ia0VA0DZDAc=
